import type {
  BackendCardCategory,
  BackendCardTemplateCatalogEntry,
  BackendCardTemplateDetail,
} from "../contracts/cardsHttpTypes";

const cardTemplateCatalog: BackendCardTemplateDetail[] = [
  {
    cardTemplateId: "card-birthday-confetti-frame",
    slug: "birthday-confetti-frame",
    title: "Birthday confetti frame",
    category: "birthday",
    occasion: "Birthday celebration",
    description:
      "A cheerful birthday card layout with confetti accents, headline space, and a personal message block.",
    supportedFields: [
      {
        fieldId: "recipient_name",
        label: "Recipient name",
        kind: "text",
        placeholder: "Avery",
        required: true,
        helpText: "Shown in the main greeting.",
      },
      {
        fieldId: "event_title",
        label: "Headline",
        kind: "text",
        placeholder: "Happy Birthday!",
        required: true,
        helpText: "Primary celebratory headline.",
      },
      {
        fieldId: "short_message",
        label: "Short message",
        kind: "multiline",
        placeholder: "Wishing you a joyful year ahead.",
        required: true,
        helpText: "Short personal note shown in the body.",
      },
      {
        fieldId: "sender_name",
        label: "Sender name",
        kind: "text",
        placeholder: "Jordan",
        required: false,
        helpText: "Optional sign-off in the footer.",
      },
      {
        fieldId: "theme_option",
        label: "Theme",
        kind: "theme_option",
        required: true,
        helpText: "Planning-only local theme switch for the preview shell.",
        options: [
          { value: "sunrise", label: "Sunrise" },
          { value: "berry", label: "Berry" },
          { value: "mint", label: "Mint" },
        ],
      },
      {
        fieldId: "font_option",
        label: "Font style",
        kind: "font_option",
        required: true,
        helpText: "Planning-only local font option for the preview shell.",
        options: [
          { value: "classic", label: "Classic" },
          { value: "celebration", label: "Celebration" },
        ],
      },
    ],
    layout: "portrait",
    themeTokens: {
      background: "#fff7ed",
      foreground: "#7c2d12",
      accent: "#fb7185",
      border: "#fdba74",
    },
    outputAspectRatio: "4:5",
    safeUseLabel: "Decorative greeting card template only",
    samplePreviewKind: "static_sample_only",
    draftCreditEstimate: {
      label: "No credits in MVP. Future export/generation costs remain planning only.",
      planningOnly: true,
    },
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "Uses original generic decorative styling only. No copyrighted characters or brand assets.",
    disclaimer:
      "Static card template MVP only. No AI generation, download, share, QR code, or project saving is enabled.",
  },
  {
    cardTemplateId: "card-invitation-garden-party",
    slug: "invitation-garden-party",
    title: "Garden party invitation",
    category: "invitation",
    occasion: "General invitation",
    description:
      "A cheerful invitation card shell for celebrations, gatherings, and private events with names, time, venue, and message fields.",
    supportedFields: [
      {
        fieldId: "event_title",
        label: "Invitation title",
        kind: "text",
        placeholder: "You're Invited",
        required: true,
        helpText: "Primary invitation headline.",
      },
      {
        fieldId: "recipient_name",
        label: "Host or guest of honor",
        kind: "text",
        placeholder: "Garden Brunch with Priya",
        required: true,
        helpText: "Shown as the main event line.",
      },
      {
        fieldId: "event_date",
        label: "Date",
        kind: "date",
        required: true,
        helpText: "Optional date text shown in the card preview.",
      },
      {
        fieldId: "event_time",
        label: "Time",
        kind: "time",
        required: false,
        helpText: "Optional event start time.",
      },
      {
        fieldId: "venue_address",
        label: "Venue",
        kind: "multiline",
        placeholder: "Willow Courtyard, 89 Orchard Way",
        required: true,
        helpText: "Venue or address text shown in the body.",
      },
      {
        fieldId: "short_message",
        label: "Invitation note",
        kind: "multiline",
        placeholder: "Join us for an afternoon of food, music, and conversation.",
        required: false,
        helpText: "Optional invitation note.",
      },
    ],
    layout: "portrait",
    themeTokens: {
      background: "#f7fff7",
      foreground: "#14532d",
      accent: "#22c55e",
      border: "#bbf7d0",
    },
    outputAspectRatio: "4:5",
    safeUseLabel: "Decorative invitation template only",
    samplePreviewKind: "static_sample_only",
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "Generic invitation styling only. No official seals, copyrighted characters, or misleading institutional design.",
    disclaimer:
      "Static invitation template MVP only. No download, share, QR code, hosted page, or project save exists in this phase.",
  },
  {
    cardTemplateId: "card-wedding-elegant-invite",
    slug: "wedding-elegant-invite",
    title: "Elegant wedding invitation",
    category: "wedding",
    occasion: "Wedding invitation",
    description:
      "A formal wedding invitation layout with names, date, venue, and a short message area.",
    supportedFields: [
      {
        fieldId: "event_title",
        label: "Event title",
        kind: "text",
        placeholder: "Together with their families",
        required: true,
        helpText: "Optional preface line.",
      },
      {
        fieldId: "recipient_name",
        label: "Couple names",
        kind: "text",
        placeholder: "Riley and Sam",
        required: true,
        helpText: "Primary headline for the invitation.",
      },
      {
        fieldId: "event_date",
        label: "Date",
        kind: "date",
        required: true,
        helpText: "Shown as the event date.",
      },
      {
        fieldId: "event_time",
        label: "Time",
        kind: "time",
        required: false,
        helpText: "Optional ceremony time.",
      },
      {
        fieldId: "venue_address",
        label: "Venue",
        kind: "multiline",
        placeholder: "Rose Garden Hall, 123 Willow Lane",
        required: true,
        helpText: "Venue or address text shown in the body.",
      },
      {
        fieldId: "short_message",
        label: "Message",
        kind: "multiline",
        placeholder: "Join us for an evening of celebration.",
        required: false,
        helpText: "Optional invitation note.",
      },
    ],
    layout: "portrait",
    themeTokens: {
      background: "#fffaf5",
      foreground: "#4a2c2a",
      accent: "#b08d57",
      border: "#ead7c3",
    },
    outputAspectRatio: "4:5",
    safeUseLabel: "Decorative invitation template only",
    samplePreviewKind: "static_sample_only",
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "Generic invitation styling only. No protected logos, official emblems, or misleading official-document treatment.",
    disclaimer:
      "Local preview only. Download, hosted sharing, QR codes, and persistence are not enabled in this phase.",
  },
  {
    cardTemplateId: "card-eid-crescent-greeting",
    slug: "eid-crescent-greeting",
    title: "Eid crescent greeting",
    category: "eid",
    occasion: "Eid greeting",
    description:
      "A festive Eid greeting card shell with a decorative crescent motif, greeting headline, and blessing message.",
    supportedFields: [
      {
        fieldId: "event_title",
        label: "Greeting title",
        kind: "text",
        placeholder: "Eid Mubarak",
        required: true,
        helpText: "Main greeting headline.",
      },
      {
        fieldId: "recipient_name",
        label: "Recipient name",
        kind: "text",
        placeholder: "Friends and family",
        required: false,
        helpText: "Optional recipient line.",
      },
      {
        fieldId: "short_message",
        label: "Message",
        kind: "multiline",
        placeholder: "Wishing you peace, joy, and blessings.",
        required: true,
        helpText: "Main body message.",
      },
      {
        fieldId: "sender_name",
        label: "Sender name",
        kind: "text",
        placeholder: "From the Khan family",
        required: false,
        helpText: "Optional sign-off.",
      },
    ],
    layout: "portrait",
    themeTokens: {
      background: "#f7f6ed",
      foreground: "#164e63",
      accent: "#d4af37",
      border: "#cbd5e1",
    },
    outputAspectRatio: "4:5",
    safeUseLabel: "Decorative holiday greeting card template only",
    samplePreviewKind: "static_sample_only",
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "Generic decorative holiday styling only. No copyrighted characters or third-party logos.",
    disclaimer:
      "Static card template only. AI generation and real downloads are not enabled yet.",
  },
  {
    cardTemplateId: "card-christmas-evergreen-wishes",
    slug: "christmas-evergreen-wishes",
    title: "Christmas evergreen wishes",
    category: "christmas",
    occasion: "Christmas greeting",
    description:
      "A warm Christmas greeting card shell with a festive headline, recipient line, and short message block.",
    supportedFields: [
      {
        fieldId: "event_title",
        label: "Greeting title",
        kind: "text",
        placeholder: "Merry Christmas",
        required: true,
        helpText: "Primary holiday headline.",
      },
      {
        fieldId: "recipient_name",
        label: "Recipient",
        kind: "text",
        placeholder: "Friends and family",
        required: false,
        helpText: "Optional recipient line.",
      },
      {
        fieldId: "short_message",
        label: "Message",
        kind: "multiline",
        placeholder: "Wishing you warmth, joy, and a peaceful holiday season.",
        required: true,
        helpText: "Short holiday message.",
      },
      {
        fieldId: "sender_name",
        label: "Sender",
        kind: "text",
        placeholder: "From the Patel family",
        required: false,
        helpText: "Optional sign-off.",
      },
    ],
    layout: "portrait",
    themeTokens: {
      background: "#fefce8",
      foreground: "#14532d",
      accent: "#b91c1c",
      border: "#bbf7d0",
    },
    outputAspectRatio: "4:5",
    safeUseLabel: "Decorative holiday greeting card template only",
    samplePreviewKind: "static_sample_only",
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "Uses original seasonal styling only. No copyrighted characters, licensed mascots, or brand logos.",
    disclaimer:
      "Static holiday card MVP only. AI generation, downloads, hosted sharing, and QR features are not enabled.",
  },
  {
    cardTemplateId: "card-holi-color-splash",
    slug: "holi-color-splash",
    title: "Holi color splash greeting",
    category: "holi",
    occasion: "Holi greeting",
    description:
      "A lively Holi greeting shell with bright color accents, greeting title, and blessing message fields.",
    supportedFields: [
      {
        fieldId: "event_title",
        label: "Greeting title",
        kind: "text",
        placeholder: "Happy Holi",
        required: true,
        helpText: "Main greeting title.",
      },
      {
        fieldId: "recipient_name",
        label: "Recipient",
        kind: "text",
        placeholder: "To our colorful crew",
        required: false,
        helpText: "Optional recipient line.",
      },
      {
        fieldId: "short_message",
        label: "Message",
        kind: "multiline",
        placeholder: "Wishing you joy, laughter, and bright moments all season long.",
        required: true,
        helpText: "Short celebratory message.",
      },
      {
        fieldId: "sender_name",
        label: "Sender",
        kind: "text",
        placeholder: "From Asha",
        required: false,
        helpText: "Optional sign-off.",
      },
    ],
    layout: "portrait",
    themeTokens: {
      background: "#fff7ed",
      foreground: "#7c2d12",
      accent: "#ec4899",
      border: "#fdba74",
    },
    outputAspectRatio: "4:5",
    safeUseLabel: "Decorative festival greeting template only",
    samplePreviewKind: "static_sample_only",
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "Original celebratory styling only. No copyrighted art, brand logos, or deceptive official-event presentation.",
    disclaimer:
      "Local preview shell only. Download, share, QR, and project saving are not enabled in this phase.",
  },
  {
    cardTemplateId: "card-halloween-moonlit-party",
    slug: "halloween-moonlit-party",
    title: "Halloween moonlit party",
    category: "halloween",
    occasion: "Halloween invitation",
    description:
      "A playful Halloween invitation shell with event title, host line, date, venue, and short message fields.",
    supportedFields: [
      {
        fieldId: "event_title",
        label: "Event title",
        kind: "text",
        placeholder: "Spooky Night Party",
        required: true,
        helpText: "Main invitation title.",
      },
      {
        fieldId: "recipient_name",
        label: "Host line",
        kind: "text",
        placeholder: "Hosted by The Rivera Family",
        required: false,
        helpText: "Optional host line.",
      },
      {
        fieldId: "event_date",
        label: "Date",
        kind: "date",
        required: true,
        helpText: "Optional date shown in the body.",
      },
      {
        fieldId: "venue_address",
        label: "Venue",
        kind: "multiline",
        placeholder: "Maple Hall, 14 Lantern Street",
        required: true,
        helpText: "Venue or address text.",
      },
      {
        fieldId: "short_message",
        label: "Message",
        kind: "multiline",
        placeholder: "Costumes welcome and candy encouraged.",
        required: false,
        helpText: "Short event note.",
      },
    ],
    layout: "portrait",
    themeTokens: {
      background: "#111827",
      foreground: "#f9fafb",
      accent: "#f97316",
      border: "#7c3aed",
    },
    outputAspectRatio: "4:5",
    safeUseLabel: "Decorative seasonal invitation template only",
    samplePreviewKind: "static_sample_only",
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "Original seasonal styling only. No copyrighted characters, logos, or branded holiday assets.",
    disclaimer:
      "Static template MVP only. No AI generation, no QR, no share page, and no file export are enabled.",
  },
  {
    cardTemplateId: "card-business-contact-minimal",
    slug: "business-contact-minimal",
    title: "Minimal business contact card",
    category: "business",
    occasion: "Business contact card",
    description:
      "A clean decorative business contact card shell for brand name, contact details, and optional website/social handle.",
    supportedFields: [
      {
        fieldId: "business_name",
        label: "Business name",
        kind: "text",
        placeholder: "Northfield Studio",
        required: true,
        helpText: "Primary organization or brand name.",
      },
      {
        fieldId: "recipient_name",
        label: "Contact name",
        kind: "text",
        placeholder: "Taylor Reed",
        required: true,
        helpText: "Primary contact name.",
      },
      {
        fieldId: "phone",
        label: "Phone",
        kind: "phone",
        placeholder: "(555) 010-2020",
        required: false,
        helpText: "Optional phone number shown as plain text only.",
      },
      {
        fieldId: "email",
        label: "Email",
        kind: "email",
        placeholder: "hello@example.com",
        required: false,
        helpText: "Optional contact email.",
      },
      {
        fieldId: "website",
        label: "Website",
        kind: "url",
        placeholder: "https://example.com",
        required: false,
        helpText: "Optional website text for the card shell.",
      },
      {
        fieldId: "social_handle",
        label: "Social handle",
        kind: "text",
        placeholder: "@northfieldstudio",
        required: false,
        helpText: "Optional social handle text.",
      },
    ],
    layout: "landscape",
    themeTokens: {
      background: "#f8fafc",
      foreground: "#0f172a",
      accent: "#2563eb",
      border: "#cbd5e1",
    },
    outputAspectRatio: "16:9",
    safeUseLabel:
      "Decorative non-financial business contact template only. Not a payment or bank card.",
    samplePreviewKind: "static_sample_only",
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "No payment logos, bank marks, card numbers, CVV, expiry, or deceptive financial styling.",
    disclaimer:
      "This is a decorative contact card shell only. No hosted sharing, QR code, or account persistence is available.",
  },
  {
    cardTemplateId: "card-visiting-classic-contact",
    slug: "visiting-classic-contact",
    title: "Classic visiting card shell",
    category: "visiting",
    occasion: "Visiting card",
    description:
      "A classic visiting card shell for name, title, phone, email, website, and optional social handle without any financial-card styling.",
    supportedFields: [
      {
        fieldId: "recipient_name",
        label: "Name",
        kind: "text",
        placeholder: "Morgan Lee",
        required: true,
        helpText: "Primary contact name.",
      },
      {
        fieldId: "business_name",
        label: "Business or role",
        kind: "text",
        placeholder: "Creative Director",
        required: true,
        helpText: "Role, studio, or business line.",
      },
      {
        fieldId: "phone",
        label: "Phone",
        kind: "phone",
        placeholder: "(555) 010-0101",
        required: false,
        helpText: "Optional phone number shown as plain text only.",
      },
      {
        fieldId: "email",
        label: "Email",
        kind: "email",
        placeholder: "morgan@example.com",
        required: false,
        helpText: "Optional email line.",
      },
      {
        fieldId: "website",
        label: "Website",
        kind: "url",
        placeholder: "https://studio.example.com",
        required: false,
        helpText: "Optional website text.",
      },
      {
        fieldId: "social_handle",
        label: "Social handle",
        kind: "text",
        placeholder: "@morgancreates",
        required: false,
        helpText: "Optional social handle.",
      },
    ],
    layout: "landscape",
    themeTokens: {
      background: "#ffffff",
      foreground: "#111827",
      accent: "#0891b2",
      border: "#cbd5e1",
    },
    outputAspectRatio: "16:9",
    safeUseLabel:
      "Decorative non-financial visiting card template only. Not a bank, payment, or identity card.",
    samplePreviewKind: "static_sample_only",
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "Generic contact-card styling only. No payment network marks, bank logos, numbers, CVV, expiry, or deceptive financial treatment.",
    disclaimer:
      "Local preview shell only. No download, hosted page, QR, share, or account-owned card storage exists.",
  },
  {
    cardTemplateId: "card-gift-note-tag",
    slug: "gift-note-tag",
    title: "Gift note tag",
    category: "gift",
    occasion: "Gift note",
    description:
      "A compact decorative gift note template with recipient name, sender name, and a short message.",
    supportedFields: [
      {
        fieldId: "recipient_name",
        label: "To",
        kind: "text",
        placeholder: "Maya",
        required: true,
        helpText: "Recipient name.",
      },
      {
        fieldId: "sender_name",
        label: "From",
        kind: "text",
        placeholder: "Alex",
        required: true,
        helpText: "Sender name.",
      },
      {
        fieldId: "short_message",
        label: "Gift note",
        kind: "multiline",
        placeholder: "Hope this brings you joy.",
        required: false,
        helpText: "Optional short note.",
      },
    ],
    layout: "square",
    themeTokens: {
      background: "#fffdf7",
      foreground: "#78350f",
      accent: "#f59e0b",
      border: "#fcd34d",
    },
    outputAspectRatio: "1:1",
    safeUseLabel: "Decorative gift card note only",
    samplePreviewKind: "static_sample_only",
    status: "published",
    lastReviewedAt: "2026-05-23T00:00:00.000Z",
    sourceOwnershipNotes:
      "Decorative gift-note styling only. Not a stored-value card and not a branded gift certificate.",
    disclaimer:
      "Static local preview only. No download, redemption, QR, share, or storage behavior exists in this MVP.",
  },
];

export const cardCategories: BackendCardCategory[] = [
  "birthday",
  "wedding",
  "invitation",
  "eid",
  "christmas",
  "holi",
  "halloween",
  "business",
  "visiting",
  "gift",
];

export const getCardTemplateCatalog = (): BackendCardTemplateCatalogEntry[] =>
  cardTemplateCatalog;

export const getCardTemplateDetailById = (
  cardTemplateId: string,
): BackendCardTemplateDetail | undefined =>
  cardTemplateCatalog.find((template) => template.cardTemplateId === cardTemplateId);
